### ISSUE TITLE
Use rubycas-server 1.0 in integrated tests

### ISSUE THREAD

**Issue by rsutphin** [NUARIG/aker#6]
The integrated tests for Aker's CAS support are based on rubycas-server. Rubycas-server 1.0 was released a few days ago. Aker's integrated test runner doesn't work with it out of the box; fix it so that it can.

In addition to the general benefit of keeping up with bugfixes, etc., rubycas-server < 1.0 doesn't work on Ruby 1.9 at all. Consequently, Aker's CAS integrated tests are disabled on that platform. Hopefully 1.0 will work with Ruby 1.9, meaning we can re-enable those tests.

**Comment by hannahwhy** [comment]
This seems like something that's best taken care of before #7 (going to need to write CAS tests for #7), so I'll see if I can get it done.

**Comment by hannahwhy** [comment]
Some CAS proxy scenarios still don't work under 1.9.2-p290, but I (or someone else) will solve that under #8.  For now, though, other supported platforms are ok with RubyCAS-Server ~> 1.0.
